// Champions Database
const championsDatabase = {
  regions: [
    {
      id: "void",
      name: "Hư Không",
      icon: "🕳️",
      existingChampions: [
        {
          id: "belveth",
          name: "Bel'Veth",
          icon: "👑",
          role: "Đấu Sĩ",
          region: "void",
          lore: "Nữ hoàng Hư Không, sinh ra từ thành phố bị nuốt chửng, muốn tái tạo Runeterra theo hình ảnh méo mó của mình.",
        },
        {
          id: "kaisa",
          name: "Kai'Sa",
          icon: "🏹",
          role: "Xạ Thủ",
          region: "void",
          lore: "Người sống sót là con người, hòa nhập với lớp vỏ Hư Không sống, chiến đấu chống lại Hư Không nhưng bị coi là quái vật.",
        },
        {
          id: "kassadin",
          name: "Kassadin",
          icon: "⚡",
          role: "Sát Thủ",
          region: "void",
          lore: "Kẻ du hành, tìm cách trả thù Hư Không vì đã nuốt chửng gia đình mình, sử dụng các tạo tác Hư Không.",
        },
        {
          id: "chogath",
          name: "Cho'Gath",
          icon: "👹",
          role: "Đỡ Đòn",
          region: "void",
          lore: "Khủng bố của Hư Không, sinh vật bản năng nguyên thủy, nuốt chửng để phát triển kích thước và sức mạnh.",
        },
        {
          id: "khazix",
          name: "Kha'Zix",
          icon: "🦂",
          role: "Sát Thủ",
          region: "void",
          lore: "Kẻ săn mồi siêu tiến hóa, tiêu thụ con mồi mạnh mẽ nhất để thích nghi và trở nên hoàn hảo hơn.",
        },
        {
          id: "malzahar",
          name: "Malzahar",
          icon: "🔮",
          role: "Pháp Sư",
          region: "void",
          lore: "Tiên tri, tin rằng Hư Không là sự cứu rỗi của Runeterra, truyền bá ảnh hưởng và triệu hồi Sinh vật Hư Không.",
        },
        {
          id: "velkoz",
          name: "Vel'Koz",
          icon: "👁️",
          role: "Pháp Sư",
          region: "void",
          lore: "Con Mắt Hư Không, sinh vật Hư Không cổ xưa nhất, tìm kiếm kiến thức bằng cách hủy diệt và phân tích.",
        },
        {
          id: "reksai",
          name: "Rek'Sai",
          icon: "🐛",
          role: "Đấu Sĩ",
          region: "void",
          lore: "Kẻ đào hang Hư Không, kẻ săn mồi không ngừng, đào hầm để phục kích và nuốt chửng con mồi.",
        },
        {
          id: "kogmaw",
          name: "Kog'Maw",
          icon: "👄",
          role: "Xạ Thủ",
          region: "void",
          lore: "Miệng của Vực Thẳm, sinh vật tò mò, nuốt chửng để hiểu thế giới, sự ngây thơ nguy hiểm.",
        },
      ],
      newChampions: [
        {
          name: "Xylos, Kẻ Gặm Nhấm Ký Ức",
          icon: "🧠",
          role: "Hỗ Trợ/Pháp Sư",
          region: "void",
          lore: "Ký sinh trùng tâm linh từ Biển Oải Hương, tiêu thụ ký ức và bản sắc, để lại sự trống rỗng cho Bel'Veth tái tạo.",
          skills: [
            "Q: Lời Thì Thầm Hư Vô",
            "W: Vùng Đất Quên Lãng",
            "E: Liên Kết Ký Ức",
            "R: Đại Tiệc Ký Ức",
          ],
        },
        {
          name: "Aethel, Hồn Ma Bị Bóp Méo",
          icon: "👻",
          role: "Đỡ Đòn/Đấu Sĩ",
          region: "void",
          lore: "Sinh vật nguyên thủy bị Hư Không biến dạng, lai giữa sự sống và hư vô.",
          skills: [
            "Q: Chấn Động Hư Vô",
            "W: Tái Tạo Vô Định",
            "E: Vết Nứt Kéo Lê",
            "R: Tiếng Vọng Của Sự Hủy Diệt",
          ],
        },
        {
          name: "Umbra, Kẻ Thao Túng Bóng Tối",
          icon: "🌑",
          role: "Sát Thủ/Đấu Sĩ",
          region: "void",
          lore: "Thực thể ý thức từ bóng tối còn sót lại sau khi Bel'Veth tiêu thụ, thao túng bóng tối và nỗi sợ hãi.",
          skills: [
            "Q: Lưỡi Hái Bóng Đêm",
            "W: Vực Thẳm Nỗi Sợ",
            "E: Lướt Bóng",
            "R: Đêm Tận Thế",
          ],
        },
        {
          name: "Chronos, Kẻ Ăn Mòn Thời Gian",
          icon: "⏰",
          role: "Pháp Sư/Kiểm Soát",
          region: "void",
          lore: "Thực thể Hư Không biến dạng từ dòng chảy thời gian, làm suy yếu thời gian của kẻ thù.",
          skills: [
            "Q: Vết Nứt Thời Gian",
            "W: Vòng Lặp Vô Tận",
            "E: Phân Rã Nhanh",
            "R: Thời Khắc Hư Vô",
          ],
        },
        {
          name: "Lithos, Kẻ Biến Dạng Địa Hình",
          icon: "🗿",
          role: "Đấu Sĩ/Đỡ Đòn",
          region: "void",
          lore: "Sinh vật khổng lồ từ sự tiêu thụ và biến dạng của vỏ Runeterra, bóp méo và tái tạo địa hình.",
          skills: [
            "Q: Nắm Đấm Địa Hình",
            "W: Hố Sâu Nuốt Chửng",
            "E: Lướt Địa Hình",
            "R: Biến Đổi Cảnh Quan",
          ],
        },
      ],
    },
    {
      id: "shadowisles",
      name: "Quần Đảo Bóng Đêm",
      icon: "👻",
      existingChampions: [
        {
          id: "thresh",
          name: "Thresh",
          icon: "⛓️",
          role: "Hỗ Trợ",
          region: "shadowisles",
          lore: "Một linh hồn tàn bạo và xảo quyệt, Thresh từng là một cai ngục độc ác khi còn sống.",
        },
        {
          id: "viego",
          name: "Viego",
          icon: "👑",
          role: "Đấu Sĩ",
          region: "shadowisles",
          lore: "Một vị vua bi thảm và đầy thù hận, Viego đã giải phóng Đại Suy Vong.",
        },
        {
          id: "karthus",
          name: "Karthus",
          icon: "💀",
          role: "Pháp Sư",
          region: "shadowisles",
          lore: "Một kẻ báo hiệu linh hồn, Karthus coi cái chết không phải là kết thúc mà là một dạng siêu thoát.",
        },
        {
          id: "kalista",
          name: "Kalista",
          icon: "🏹",
          role: "Xạ Thủ",
          region: "shadowisles",
          lore: "Tinh thần báo thù, Kalista bị phản bội và chết, giờ săn lùng những kẻ bội bạc.",
        },
        {
          id: "hecarim",
          name: "Hecarim",
          icon: "🐴",
          role: "Đấu Sĩ",
          region: "shadowisles",
          lore: "Kỵ sĩ chiến tranh ma quái, dẫn đầu đoàn kỵ binh ma trong trận chiến vĩnh cửu.",
        },
        {
          id: "yorick",
          name: "Yorick",
          icon: "⚰️",
          role: "Đấu Sĩ",
          region: "shadowisles",
          lore: "Người đào mộ cuối cùng, cứu rỗi linh hồn bị mắc kẹt trong Màn Sương Đen.",
        },
        {
          id: "maokai",
          name: "Maokai",
          icon: "🌳",
          role: "Đỡ Đòn",
          region: "shadowisles",
          lore: "Cây cổ thụ sống, bảo vệ tàn tích cuối cùng của Quần Đảo Phước Lành.",
        },
      ],
      newChampions: [
        {
          name: "Lyra, Người Dệt Tiếng Vọng",
          icon: "🎶",
          role: "Pháp Sư",
          region: "shadowisles",
          lore: "Nữ thi sĩ bị biến chất bởi Màn Sương Đen, dệt nên những giai điệu ma quái.",
          skills: [
            "Q: Hợp Âm Bất Hòa",
            "W: Mạng Lưới Ký Ức",
            "E: Giai Điệu Vỡ Tan",
            "R: Khúc Bi Tráng",
          ],
        },
        {
          name: "Mortis, Kẻ Thu Hoạch Linh Hồn",
          icon: "💀",
          role: "Sát Thủ",
          region: "shadowisles",
          lore: "Thợ săn linh hồn, thu hoạch nỗi đau khổ để nuôi dưỡng sức mạnh bóng tối.",
          skills: [
            "Q: Lưỡi Hái Linh Hồn",
            "W: Bẫy Ma Quái",
            "E: Bước Nhảy Bóng Tối",
            "R: Thu Hoạch Tuyệt Vọng",
          ],
        },
      ],
    },
    {
      id: "demacia",
      name: "Demacia",
      icon: "⚜️",
      existingChampions: [
        {
          id: "garen",
          name: "Garen",
          icon: "🛡️",
          role: "Đấu Sĩ",
          region: "demacia",
          lore: "Một chiến binh cao quý và là biểu tượng của Demacia.",
        },
        {
          id: "lux",
          name: "Lux",
          icon: "✨",
          role: "Pháp Sư",
          region: "demacia",
          lore: "Một pháp sư ánh sáng mạnh mẽ, phải che giấu khả năng của mình.",
        },
        {
          id: "jarvan",
          name: "Jarvan IV",
          icon: "👑",
          role: "Đỡ Đòn",
          region: "demacia",
          lore: "Hoàng tử của Demacia, dẫn đầu quân đội bảo vệ đất nước.",
        },
        {
          id: "shyvana",
          name: "Shyvana",
          icon: "🐉",
          role: "Đấu Sĩ",
          region: "demacia",
          lore: "Nữ rồng nửa người, chiến đấu để chứng minh lòng trung thành với Demacia.",
        },
        {
          id: "fiora",
          name: "Fiora",
          icon: "⚔️",
          role: "Đấu Sĩ",
          region: "demacia",
          lore: "Đấu kiếm gia kiêu hãnh nhất Demacia, tìm kiếm những thử thách xứng đáng.",
        },
      ],
      newChampions: [
        {
          name: "Seraphina, Người Canh Gác Lumina",
          icon: "✨",
          role: "Hỗ Trợ",
          region: "demacia",
          lore: "Pháp sư đã tìm ra cách thanh lọc ma thuật bằng ánh sáng tinh khiết.",
          skills: [
            "Q: Tia Sáng Trói Buộc",
            "W: Hào Quang Bảo Vệ",
            "E: Cột Sáng Phục Hồi",
            "R: Bình Minh Rạng Rỡ",
          ],
        },
      ],
    },
    {
      id: "noxus",
      name: "Noxus",
      icon: "🗡️",
      existingChampions: [
        {
          id: "darius",
          name: "Darius",
          icon: "🪓",
          role: "Đấu Sĩ",
          region: "noxus",
          lore: "Tướng quân không khoan nhượng của Noxus, biểu tượng của sức mạnh và quyết tâm.",
        },
        {
          id: "katarina",
          name: "Katarina",
          icon: "🗡️",
          role: "Sát Thủ",
          region: "noxus",
          lore: "Sát thủ lưỡng dao nguy hiểm nhất của Noxus, nhanh như chớp và tàn nhẫn.",
        },
        {
          id: "swain",
          name: "Swain",
          icon: "🦅",
          role: "Pháp Sư",
          region: "noxus",
          lore: "Thống suất cao cấp của Noxus, sử dụng ma thuật quỷ dữ để thống trị.",
        },
      ],
      newChampions: [
        {
          name: "Vex'thar, Đại Tướng Máu",
          icon: "⚔️",
          role: "Đấu Sĩ",
          region: "noxus",
          lore: "Chiến binh tàn bạo từ vùng biên giới, sử dụng máu kẻ thù để tăng sức mạnh.",
          skills: [
            "Q: Thối Máu",
            "W: Phẫn Nộ Tàn Bạo",
            "E: Lướt Sát Thương",
            "R: Cuồng Máu",
          ],
        },
      ],
    },
    {
      id: "ionia",
      name: "Ionia",
      icon: "🌸",
      existingChampions: [
        {
          id: "yasuo",
          name: "Yasuo",
          icon: "🌪️",
          role: "Đấu Sĩ",
          region: "ionia",
          lore: "Kiếm sĩ bất tài với lời nguyền gió, tìm kiếm sự cứu rỗi và tha thứ.",
        },
        {
          id: "ahri",
          name: "Ahri",
          icon: "🦊",
          role: "Pháp Sư",
          region: "ionia",
          lore: "Hồ ly chín đuôi, tìm kiếm nguồn gốc thật sự của mình giữa hai thế giới.",
        },
        {
          id: "irelia",
          name: "Irelia",
          icon: "💃",
          role: "Đấu Sĩ",
          region: "ionia",
          lore: "Vũ công lưỡi dao, dẫn đầu kháng chiến chống lại sự xâm lược của Noxus.",
        },
      ],
      newChampions: [
        {
          name: "Kenshin, Thiền Sư Kiếm Đạo",
          icon: "🧘",
          role: "Đấu Sĩ",
          region: "ionia",
          lore: "Kiếm sĩ tu tâm, cân bằng giữa tĩnh tâm và chiến đấu quyết liệt.",
          skills: [
            "Q: Thiền Định",
            "W: Kiếm Khí",
            "E: Bước Nhảy Linh Hoạt",
            "R: Thần Kiếm Vô Ngã",
          ],
        },
      ],
    },
    {
      id: "piltover",
      name: "Piltover",
      icon: "⚙️",
      existingChampions: [
        {
          id: "jayce",
          name: "Jayce",
          icon: "🔨",
          role: "Đấu Sĩ",
          region: "piltover",
          lore: "Nhà phát minh thiên tài, tạo ra vũ khí biến hình tiên tiến để bảo vệ Piltover.",
        },
        {
          id: "caitlyn",
          name: "Caitlyn",
          icon: "🎯",
          role: "Xạ Thủ",
          region: "piltover",
          lore: "Cảnh sát trưởng Piltover, nổi tiếng với khả năng bắn tỉa hoàn hảo.",
        },
        {
          id: "vi",
          name: "Vi",
          icon: "👊",
          role: "Đấu Sĩ",
          region: "piltover",
          lore: "Cảnh sát hung hãn với đôi găng tay Hextech, thích giải quyết vấn đề bằng nắm đấm.",
        },
      ],
      newChampions: [
        {
          name: "Gearwick, Thợ Máy Thiên Tài",
          icon: "🔧",
          role: "Hỗ Trợ",
          region: "piltover",
          lore: "Nhà phát minh trẻ tuổi, tạo ra các thiết bị Hextech hỗ trợ đồng minh trong chiến đấu.",
          skills: [
            "Q: Rô-bốt Tu Sửa",
            "W: Tháp Pháo Tự Động",
            "E: Tăng Tốc Hextech",
            "R: Máy Móc Đại Chiến",
          ],
        },
      ],
    },
  ],
  specialChampions: {
    apocalypseKnight: {
      id: "apocalypse",
      name: "Kỵ Sĩ Khải Huyền",
      icon: "🐎",
      role: "Lai/Đa Dạng",
      region: "special",
      lore: "Tướng có khả năng biến đổi thành bốn dạng khác nhau: Chiến Tranh (AD), Nạn Đói (AP), Dịch Bệnh (Thích Ứng), Cái Chết (Tank).",
      skills: [
        "Dạng Chiến Tranh - Đấu Sĩ AD",
        "Dạng Nạn Đói - Pháp Sư AP",
        "Dạng Dịch Bệnh - Sát Thương Thích Ứng",
        "Dạng Cái Chết - Tank/Kiểm Soát",
      ],
      special: true,
    },
  },
};

// Export for use in other files
if (typeof module !== "undefined" && module.exports) {
  module.exports = championsDatabase;
}
