// Demacia Region Data
const demaciaData = {
  id: "demacia",
  name: "Demacia",
  icon: "⚜️",
  lore: `A. Các Giá Trị Cốt Lõi Của Demacia & Những Sắc Thái Của Chúng
Bản sắc của Demacia ăn sâu vào các giá trị cốt lõi của nó. Công dân "vô cùng tự hào về di sản văn hóa của họ" và tự coi mình là "kiêu hãnh và công bằng". Quốc gia này đề cao "lòng dũng cảm, sức mạnh và sự chính trực", được thể hiện qua "sức mạnh quân sự đáng gờm" và "kỷ luật kiên định". Điều này bao gồm sự chấp nhận cái chết một cách kiên cường, vì "một Demacia chân chính sẽ hợp tác với Cừu non vì bất kỳ người Demacia nào cũng sẽ chấp nhận số phận của mình một cách dũng cảm", một đặc điểm văn hóa có thể bị bóp méo cho những mục đích đen tối hơn. Xã hội được cấu trúc với một "hệ thống phân cấp xã hội phức tạp bao gồm pháp sư, quý tộc và mọi tầng lớp khác", với các gia đình quý tộc hùng mạnh như Crownguard (Garen, Lux, Jarvan IV) và Laurent (Fiora) nắm giữ ảnh hưởng đáng kể. Bản thân chính phủ "khá độc đoán", ngụ ý một cấu trúc quyền lực tập trung mạnh mẽ, nơi các mệnh lệnh được tuân thủ không chút nghi ngờ, ngay cả khi chúng mơ hồ về mặt đạo đức.

Sự nhấn mạnh phổ biến vào "công lý" ở Demacia không nhất thiết là khách quan. Đối với một sát thủ, "công lý" có thể được diễn giải một cách chủ quan là sự loại bỏ những cá nhân mà, mặc dù thoát khỏi sự truy tố pháp lý thông thường, được coi là mối đe dọa đối với sự ổn định hoặc lý tưởng của Demacia. Điều này đặc biệt liên quan khi xem xét "hệ thống phân cấp xã hội phức tạp", nơi các cá nhân cấp cao hoặc giàu có có thể không bị luật pháp truyền thống chạm tới. Một đặc vụ bí mật, có khả năng được chính phủ "độc đoán" cho phép, có thể hoạt động như một bàn tay báo thù vô hình, đảm bảo rằng "công lý" được thực thi, ngay cả khi điều đó có nghĩa là hoạt động ngoài nhận thức của công chúng về luật pháp. Điều này hé lộ một mặt tối hơn của "công lý" Demacia—một mặt thực dụng và có khả năng đạo đức giả. Nó cho thấy rằng việc tuân thủ nghiêm ngặt các lý tưởng công khai có thể đòi hỏi một hệ thống bóng tối, nơi các phương tiện ngoài vòng pháp luật được sử dụng để duy trì trật tự và kiểm soát, đặc biệt là trong giới tinh hoa. Điều này tạo ra sự căng thẳng giữa hình ảnh bên ngoài của Demacia và những thực tế ẩn giấu của nó.

"Nghĩa vụ" là một giá trị cốt lõi của Demacia. Một sát thủ có thể hoạt động dưới một ý thức sâu sắc về "nghĩa vụ" đối với Demacia vượt ra ngoài các luật lệ rõ ràng hoặc các nhiệm vụ công khai. Nghĩa vụ này có thể bắt nguồn từ niềm tin cá nhân của một đặc vụ nổi loạn, hoặc từ một chỉ thị bí mật được ban hành bởi một gia đình quý tộc hùng mạnh tin rằng hành động của họ là tối quan trọng cho sự sống còn lâu dài của vương quốc, ngay cả khi nhà nước không thể chính thức thừa nhận chúng. "Kỷ luật kiên định" của quân đội có thể mở rộng đến các đơn vị bí mật, được phân chia cao độ. Khái niệm này mở ra khả năng cho các phe phái nội bộ và các cuộc đấu tranh quyền lực trong Demacia. Các cách diễn giải khác nhau về "nghĩa vụ" có thể dẫn đến các hoạt động bí mật, thậm chí có thể chống lại các Demacia khác bị một nhóm cụ thể coi là mối đe dọa. Nó bổ sung các lớp âm mưu chính trị và sự mơ hồ đạo đức vào động lực nội bộ của vương quốc.

B. Mệnh Lệnh Chống Ma Thuật
Nền tảng của Demacia được xây dựng trên nỗi sợ hãi và sự cấm đoán ma thuật, được thành lập như một "nơi ẩn náu khỏi ma thuật sau Chiến Tranh Rune". Chính sách chống ma thuật khắt khe này được duy trì bằng cách sử dụng petricite - một loại đá có khả năng hấp thụ ma thuật được sử dụng để xây dựng các tòa thành và pháo đài của Demacia. Những người phù thủy bị phát hiện thường bị giam giữ, trục xuất hoặc tệ hơn. Tuy nhiên, sự thật phức tạp hơn - nhiều công dân Demacia, kể cả trong hoàng gia, bí mật sở hữu năng lực ma thuật và phải che giấu bản chất thật của mình.

C. Xung Đột Nội Bộ & Mối Đe Dọa Bên Ngoài
Mặc dù Demacia trình bày hình ảnh thống nhất, vương quốc này đang phải đối mặt với nhiều thách thức nghiêm trọng. Bên trong, sự chia rẽ xã hội đang gia tăng giữa những người ủng hộ chính sách chống ma thuật cứng rắn và những người muốn cải cách. Các gia đình quý tộc tranh giành ảnh hưởng và quyền lực, tạo ra căng thẳng chính trị. Bên ngoài, Demacia đối mặt với mối đe dọa từ Noxus - kẻ thù truyền kiếp với triết lý hoàn toàn trái ngược, cũng như các lực lượng siêu nhiên và quái vật từ những vùng đất xa xôi.

D. Địa Lý & Xã Hội
Demacia nằm ở miền trung Valoran, với thủ đô cùng tên được bao quanh bởi những bức tường petricite khổng lồ. Vương quốc này có địa hình đa dạng từ những đồng cỏ xanh tươi, rừng cây cổ thụ đến những dãy núi hùng vĩ. Xã hội Demacia được tổ chức theo hệ thống phong kiến với hoàng gia ở đỉnh cao, tiếp theo là các gia đình quý tộc, hiệp sĩ, và cuối cùng là nông dân. Giáo dục và huấn luyện quân sự được coi trọng, với nhiều học viện danh tiếng đào tạo các hiệp sĩ và chiến binh ưu tú. Kiến trúc Demacia nổi tiếng với những tòa lâu đài và nhà thờ tráng lệ, được xây dựng từ đá trắng và petricite, tạo nên vẻ đẹp uy nghiêm và thiêng liêng.`.trim(),
  existingChampions: [
    {
      id: "garen",
      name: "Garen",
      icon: "🛡️",
      role: "Đấu Sĩ",
      region: "demacia",
      lore: "Một chiến binh cao quý và là biểu tượng của Demacia.",
      releaseDate: "27/04/2010",
      loreConnections: ["Lux", "Jarvan IV"],
      weaponSummary: "Kiếm",
    },
    {
      id: "lux",
      name: "Lux",
      icon: "✨",
      role: "Pháp Sư",
      region: "demacia",
      lore: "Một pháp sư ánh sáng mạnh mẽ, phải che giấu khả năng của mình.",
      releaseDate: "19/10/2010",
      loreConnections: ["Garen", "Jarvan IV", "Galio"],
      weaponSummary: "Ma thuật",
    },
    {
      id: "jarvan",
      name: "Jarvan IV",
      icon: "👑",
      role: "Đỡ Đòn",
      region: "demacia",
      lore: "Hoàng tử của Demacia, dẫn đầu quân đội bảo vệ đất nước.",
      releaseDate: "01/03/2011",
      loreConnections: ["Garen", "Shyvana", "Xin Zhao", "Lux"],
      weaponSummary: "Thương",
    },
    {
      id: "shyvana",
      name: "Shyvana",
      icon: "🐉",
      role: "Đấu Sĩ",
      region: "demacia",
      lore: "Nữ rồng nửa người, chiến đấu để chứng minh lòng trung thành với Demacia.",
      releaseDate: "01/11/2011",
      loreConnections: ["Jarvan IV", "Xin Zhao", "Sona"],
      weaponSummary: "Nanh vuốt",
    },
    {
      id: "fiora",
      name: "Fiora",
      icon: "⚔️",
      role: "Đấu Sĩ",
      region: "demacia",
      lore: "Đấu kiếm gia kiêu hãnh nhất Demacia, tìm kiếm những thử thách xứng đáng.",
      releaseDate: "29/02/2012",
      loreConnections: ["Garen"],
      weaponSummary: "Kiếm",
    },
    {
      id: "galio",
      name: "Galio",
      role: "Đỡ Đòn",
      region: "demacia",
      lore: "Colossus ma thuật được tạo từ petricite, bảo vệ Demacia khỏi ma thuật.",
      releaseDate: "10/08/2010",
      loreConnections: ["Kayle", "Morgana", "Lux", "Sylas"],
      weaponSummary: "Nắm đấm",
    },
    {
      id: "kayle",
      name: "Kayle",
      role: "Xạ Thủ",
      region: "demacia",
      lore: "Thiên thần công lý với đôi cánh lửa, tìm kiếm trật tự tuyệt đối.",
      releaseDate: "21/02/2009",
      loreConnections: ["Galio", "Morgana", "Taric"],
      weaponSummary: "Kiếm",
    },
    {
      id: "lucian",
      name: "Lucian",
      role: "Xạ Thủ",
      region: "demacia",
      lore: "Sentinel với súng lục thiêng, săn lùng những linh hồn bóng tối.",
      releaseDate: "22/08/2013",
      loreConnections: ["Senna", "Thresh", "Hecarim"],
      weaponSummary: "Súng",
    },
    {
      id: "poppy",
      name: "Poppy",
      role: "Đỡ Đòn",
      region: "demacia",
      lore: "Yordle khiêm tốn tìm kiếm anh hùng xứng đáng với chiếc búa thiêng.",
      releaseDate: "13/01/2010",
      loreConnections: ["Không có liên kết trực tiếp được liệt kê"],
      weaponSummary: "Búa",
    },
    {
      id: "quinn",
      name: "Quinn",
      role: "Xạ Thủ",
      region: "demacia",
      lore: "Trinh sát tinh nút với người bạn đồng hành đại bàng Valor.",
      releaseDate: "01/03/2013",
      loreConnections: ["Không có liên kết trực tiếp được liệt kê"],
      weaponSummary: "Nỏ",
    },
    {
      id: "sona",
      name: "Sona",
      role: "Hỗ Trợ",
      region: "demacia",
      lore: "Nhạc sĩ câm với đàn hạc ma thuật, chữa lành bằng âm nhạc.",
      releaseDate: "21/09/2010",
      loreConnections: ["Taric", "Xin Zhao", "Ryze"],
      weaponSummary: "Ma thuật",
    },
    {
      id: "sylas",
      name: "Sylas",
      role: "Pháp Sư",
      region: "demacia",
      lore: "Cách mạng gia pháp thuật, lãnh đạo cuộc nổi dậy chống Demacia.",
      releaseDate: "25/01/2019",
      loreConnections: ["Lux", "Galio"],
      weaponSummary: "Dây xích",
    },
    {
      id: "vayne",
      name: "Vayne",
      role: "Xạ Thủ",
      region: "demacia",
      lore: "Thợ săn quái vật đêm với nỏ bạc và quyết tâm trả thù.",
      releaseDate: "10/05/2011",
      loreConnections: ["Không có liên kết trực tiếp được liệt kê"],
      weaponSummary: "Nỏ",
    },
    {
      id: "xinzhao",
      name: "Xin Zhao",
      role: "Đấu Sĩ",
      region: "demacia",
      lore: "Võ sĩ từ Ionia, trở thành vệ sĩ trung thành của hoàng gia Demacia.",
      releaseDate: "13/07/2010",
      loreConnections: ["Alistar", "Jarvan IV", "Garen", "Shyvana"],
      weaponSummary: "Thương",
    },
  ],
  newChampions: [
    {
      name: "Seraphina, Người Canh Gác Lumina",
      icon: "✨",
      role: "Hỗ Trợ",
      region: "demacia",
      lore: "Pháp sư đã tìm ra cách thanh lọc ma thuật bằng ánh sáng tinh khiết.",
      skills: [
        "Q: Tia Sáng Trói Buộc",
        "W: Hào Quang Bảo Vệ",
        "E: Cột Sáng Phục Hồi",
        "R: Bình Minh Rạng Rỡ",
      ],
    },
  ],
};
