// Noxus Region Data
const noxusData = {
  id: "noxus",
  name: "Noxus",
  icon: "🗡️",
  existingChampions: [
    {
      id: "darius",
      name: "Darius",
      icon: "🪓",
      role: "Đấu Sĩ",
      region: "noxus",
      lore: "Tướng quân không khoan nhượng của Noxus, biểu tượng của sức mạnh và quyết tâm.",
      releaseDate: "23/05/2012",
      loreConnections: ["Samira", "LeBlanc"],
      weaponSummary: "Rìu",
    },
    {
      id: "katarina",
      name: "Katarina",
      icon: "🗡️",
      role: "Sát Thủ",
      region: "noxus",
      lore: "Sát thủ lưỡng dao nguy hiểm nhất của Noxus, nhanh như chớp và tàn nhẫn.",
      releaseDate: "19/09/2009",
      loreConnections: ["Talon"],
      weaponSummary: "Dao găm",
    },
    {
      id: "swain",
      name: "Swain",
      icon: "🦅",
      role: "Pháp Sư",
      region: "noxus",
      lore: "Thống suất cao cấp của Noxus, sử dụng ma thuật quỷ dữ để thống trị.",
      releaseDate: "05/10/2010",
      loreConnections: ["LeBlanc", "Darius", "Samira"],
      weaponSummary: "Ma thuật",
    },
    {
      id: "cassiopeia",
      name: "Cassiopeia",
      role: "Pháp Sư",
      region: "noxus",
      lore: "Quý tộc Noxus bị biến thành nàng rắn, sử dụng nọc độc và ma thuật.",
      releaseDate: "14/12/2010",
      loreConnections: ["Azir"],
      weaponSummary: "Ma thuật",
    },
    {
      id: "draven",
      name: "Draven",
      role: "Xạ Thủ",
      region: "noxus",
      lore: "Đấu sĩ đấu trường kiêu ngạo, nghiện sự chú ý và vinh quang.",
      releaseDate: "06/06/2012",
      loreConnections: ["Không có liên kết trực tiếp được liệt kê"],
      weaponSummary: "Rìu",
    },
    {
      id: "kled",
      name: "Kled",
      role: "Đấu Sĩ",
      region: "noxus",
      lore: "Yordle điên cuồng cưỡi Skaarl, bảo vệ đất đai của mình một cách hung hãn.",
      releaseDate: "10/08/2016",
      loreConnections: ["Swain", "Darius", "Tristana", "Elise"],
      weaponSummary: "Súng, rìu",
    },
    {
      id: "leblanc",
      name: "LeBlanc",
      role: "Pháp Sư",
      region: "noxus",
      lore: "Pháp sư lừa đảo chủ của Rose Đen, thao túng chính trị từ bóng tối.",
      releaseDate: "02/11/2010",
      loreConnections: ["Swain", "Vladimir", "Elise"],
      weaponSummary: "Ma thuật",
    },
    {
      id: "samira",
      name: "Samira",
      role: "Xạ Thủ",
      region: "noxus",
      lore: "Thợ săn tiền thưởng phong cách, kết hợp súng và kiếm trong chiến đấu.",
      releaseDate: "21/09/2020",
      loreConnections: ["Darius", "LeBlanc"],
      weaponSummary: "Súng, kiếm",
    },
    {
      id: "sion",
      name: "Sion",
      role: "Đấu Sĩ",
      region: "noxus",
      lore: "Chiến binh bất tử được hồi sinh, vũ khí sống của Noxus.",
      releaseDate: "21/02/2009",
      loreConnections: ["Không có liên kết trực tiếp được liệt kê"],
      weaponSummary: "Rìu",
    },
    {
      id: "talon",
      name: "Talon",
      role: "Sát Thủ",
      region: "noxus",
      lore: "Sát thủ lưỡi dao im lặng, trung thành với gia đình Du Couteau.",
      releaseDate: "24/08/2011",
      loreConnections: ["Katarina"],
      weaponSummary: "Dao găm, lưỡi kiếm",
    },
    {
      id: "vladimir",
      name: "Vladimir",
      role: "Pháp Sư",
      region: "noxus",
      lore: "Ma cà rồng cổ đại thao túng máu, ảnh hưởng đến quý tộc Noxus.",
      releaseDate: "27/07/2010",
      loreConnections: ["Swain", "LeBlanc", "Elise", "Kayn"],
      weaponSummary: "Ma thuật",
    },
  ],
  newChampions: [
    {
      name: "Vex'thar, Đại Tướng Máu",
      icon: "⚔️",
      role: "Đấu Sĩ",
      region: "noxus",
      lore: "Chiến binh tàn bạo từ vùng biên giới, sử dụng máu kẻ thù để tăng sức mạnh.",
      skills: [
        "Q: Thối Máu",
        "W: Phẫn Nộ Tàn Bạo",
        "E: Lướt Sát Thương",
        "R: Cuồng Máu",
      ],
    },
  ],
};
