// Piltover Region Data
const piltoverData = {
  id: "piltover",
  name: "Piltover",
  icon: "⚙️",
  existingChampions: [
    {
      id: "jayce",
      name: "Jayce",
      icon: "🔨",
      role: "Đấu Sĩ",
      region: "piltover",
      lore: "Nhà phát minh thiên tài, tạo ra vũ khí biến hình tiên tiến để bảo vệ Piltover.",
      releaseDate: "07/07/2012",
      loreConnections: ["Viktor"],
      weaponSummary: "Búa",
      gender: "Nam",
      species: "Người",
    },
    {
      id: "caitlyn",
      name: "Caitlyn",
      icon: "🎯",
      role: "Xạ Thủ",
      region: "piltover",
      lore: "Cảnh sát trưởng Piltover, nổi tiếng với khả năng bắn tỉa hoàn hảo.",
      releaseDate: "04/01/2011",
      loreConnections: ["Vi"],
      weaponSummary: "Súng",
      gender: "Nữ",
      species: "Người",
    },
    {
      id: "vi",
      name: "Vi",
      icon: "👊",
      role: "Đấu Sĩ",
      region: "piltover",
      lore: "Cảnh sát hung hãn với đôi găng tay Hextech, thích giải quyết vấn đề bằng nắm đấm.",
      releaseDate: "19/12/2012",
      loreConnections: ["Caitlyn", "Jinx", "Ekko"],
      weaponSummary: "Găng tay",
      gender: "Nữ",
      species: "Người",
    },
    {
      id: "blitzcrank",
      name: "Blitzcrank",
      role: "Hỗ Trợ",
      region: "piltover",
      lore: "Robot thông minh được tạo ra để dọn dẹp Zaun, giờ bảo vệ những người yếu thế.",
      releaseDate: "02/09/2009",
      loreConnections: ["Orianna", "Viktor"],
      weaponSummary: "Nắm đấm",
      gender: "Nam",
      species: "Robot",
    },
    {
      id: "camille",
      name: "Camille",
      role: "Đấu Sĩ",
      region: "piltover",
      lore: "Matriarch gia tộc Ferros, sát thủ cyborg bảo vệ trật tự Piltover.",
      releaseDate: "07/12/2016",
      loreConnections: ["Renata Glasc"],
      weaponSummary: "Lưỡi kiếm",
    },
    {
      id: "corki",
      name: "Corki",
      role: "Xạ Thủ",
      region: "piltover",
      lore: "Phi công Yordle dũng cảm với máy bay chiến đấu độc đáo.",
      releaseDate: "19/09/2009",
      loreConnections: ["Heimerdinger"],
      weaponSummary: "Súng, bom",
      gender: "Nam",
      species: "Yordle",
      funFacts: [
        "Corki là một trong những tướng gốc đã có mặt khi Liên Minh Huyền Thoại ra mắt vào năm 2009.",
        "Thiết kế của Corki lấy cảm hứng từ phi công trong Thế Chiến II, với chiếc mũ bay và kính bảo hộ đặc trưng.",
        "Tên của chiếc máy bay của Corki là 'ROFL Copter', một trò đùa dựa trên thuật ngữ internet 'ROFL' (Rolling On Floor Laughing).",
        "Trước khi được làm lại, Corki có thể bắn ra cả một hàng rào dài tên lửa để giết chóc hàng loạt kẻ địch.",
        "Corki là một trong những Yordle hiếm không đến từ vùng Bandle City mà thuộc về Piltover, nơi anh ta thành lập Đội Bay Thám Hiểm.",
      ],
    },
    {
      id: "ekko",
      name: "Ekko",
      role: "Sát Thủ",
      region: "piltover",
      lore: "Thiên tài trẻ từ Zaun với khả năng điều khiển thời gian.",
      releaseDate: "29/05/2015",
      loreConnections: ["Jinx", "Vi", "Camille", "Zeri", "Renata Glasc"],
      weaponSummary: "Gậy",
    },
    {
      id: "ezreal",
      name: "Ezreal",
      role: "Xạ Thủ",
      region: "piltover",
      lore: "Nhà thám hiểm trẻ tuổi với găng tay ma thuật cổ đại.",
      releaseDate: "16/03/2010",
      loreConnections: ["Kassadin", "Lux", "Rek'Sai"],
      weaponSummary: "Ma thuật",
    },
    {
      id: "heimerdinger",
      name: "Heimerdinger",
      role: "Pháp Sư",
      region: "piltover",
      lore: "Nhà phát minh Yordle lập dị, tạo ra những phát minh kỳ diệu.",
      releaseDate: "10/10/2009",
      loreConnections: ["Corki", "Rumble", "Teemo", "Ziggs", "Veigar"],
      weaponSummary: "Tháp pháo, tên lửa, lựu đạn",
    },
    {
      id: "jinx",
      name: "Jinx",
      role: "Xạ Thủ",
      region: "piltover",
      lore: "Tội phạm điên loạn từ Zaun, gây hỗn loạn với vũ khí nổ.",
      releaseDate: "10/10/2013",
      loreConnections: ["Caitlyn", "Vi", "Ekko"],
      weaponSummary: "Súng, lựu đạn",
    },
    {
      id: "orianna",
      name: "Orianna",
      role: "Pháp Sư",
      region: "piltover",
      lore: "Vũ công cơ học với quả cầu ma thuật, tìm kiếm nhân tính.",
      releaseDate: "01/06/2011",
      loreConnections: ["Blitzcrank", "Viktor"],
      weaponSummary: "Quả cầu",
    },
    {
      id: "seraphine",
      name: "Seraphine",
      role: "Hỗ Trợ",
      region: "piltover",
      lore: "Ca sĩ trẻ tuổi với khả năng cảm nhận cảm xúc qua âm nhạc.",
      releaseDate: "29/10/2020",
      loreConnections: ["Skarner"],
      weaponSummary: "Ma thuật",
    },
    {
      id: "viktor",
      name: "Viktor",
      role: "Pháp Sư",
      region: "piltover",
      lore: "Nhà phát minh cyborg theo đuổi tiến hóa cơ học hoàn hảo.",
      releaseDate: "29/12/2011",
      loreConnections: [
        "Jayce",
        "Blitzcrank",
        "Orianna",
        "Renata Glasc",
        "Mel",
      ],
      weaponSummary: "Ma thuật",
    },
    {
      id: "zeri",
      name: "Zeri",
      role: "Xạ Thủ",
      region: "piltover",
      lore: "Cô gái trẻ từ Zaun với khả năng điều khiển điện năng.",
      releaseDate: "20/01/2022",
      loreConnections: ["Renata Glasc"],
      weaponSummary: "Súng",
    },
  ],
  newChampions: [
    {
      name: "Gearwick, Thợ Máy Thiên Tài",
      icon: "🔧",
      role: "Hỗ Trợ",
      region: "piltover",
      lore: "Nhà phát minh trẻ tuổi, tạo ra các thiết bị Hextech hỗ trợ đồng minh trong chiến đấu.",
      skills: [
        "Q: Rô-bốt Tu Sửa",
        "W: Tháp Pháo Tự Động",
        "E: Tăng Tốc Hextech",
        "R: Máy Móc Đại Chiến",
      ],
    },
  ],
};
